### ISSUE TITLE
Crash when saving image

### ISSUE THREAD

**Issue by hrkalona** [5E-324/Imagina#2]
I have changed the image size to width/height of 788 but TextureWidth  was 828 on my debug session
It is occurring on: RGBA rgba = ValToRGBA(FContext.pixelManager.Data[y * TextureWidth + x]);

This caused an out of bounds read at some point in the loop

**Comment by 5E-324** [comment]
I can't reproduce. Can you provide more information?
And what's wrong with the value of TextureWidth?

**Comment by hrkalona** [comment]
Hmm, I tried to reproduce and it did not crash again. There might exist some scenario that led to this. Anyway I am closing this for now.
